name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.15
      env:
        MIX_ENV: test
      
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Cache plt files
      uses: actions/cache@v2
      with:
        path: ./_build/plts/
        key: plt-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('mix.lock') }}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Formatting
      run: mix format --check-formatted
    - name: Code quality
      run: mix credo
    - name: Dialyzer
      run: mix dialyzer
    - name: Run Tests
      run: mix test
      env:
        DB_HOST: postgres  
    